### ISSUE TITLE
No fastq files generated

### ISSUE THREAD

**Issue by LeDillingeur** [rvolden/C3POa#1]
Hi Roger,

nice tool and paper. I was going to test your algorithm on some of my RCA nanopore data and everything seems to be going okay based on the messages I get (set the minimum length to 20 kb to make testing faster). I have successfully used the same data for INC-seq before.

$ python3 C3POa_preprocessing.py -i readsfilter.fastq -o /Users/user/C3POa/output -q 8 -l 20000 -s Splint_Aga2.fasta -c configblat.txt

Using minimap2 from your path, not the config file.
Using consensus from your path, not the config file.
Using water from your path, not the config file.
Using poa from your path, not the config file.
Using racon from your path, not the config file.
Reading and filtering fastq file
Running BLAT to find splint locations (This can take hours)
Loaded 288 letters in 1 sequences
Searched 6953471 bases in 283 sequences
Parsing BLAT output
Writing fastq output files in bins of 4000 into separate folders

However, the fastq files are nowhere to be found. The splint_reads folder stays empty. Any idea what the reason might be? The Splint_to_read_alignments.psl appears to contain sensible information.
Thanks!
Philipp

**Comment by rvolden** [comment]
Hi Philipp,

The problem was that in the preprocessing script, if your splint fasta header wasn't called "Splint", it wouldn't find it. I've pushed a change that allows the splint header to be whatever you want. Hopefully this fixes your problem.

Roger

**Comment by LeDillingeur** [comment]
Hi Roger,
That worked perfectly. I had the name "Splint" but followed by something else. Just setting it to "Splint" makes the magic happen. I haven't tried your updated version but am sure it will work.
Many thanks! 
Philipp
PS: have you thought about a way of combining your script with nanopolish (i.e. splitting the raw files according to the anchor points found with R2C2)?

**Comment by rvolden** [comment]
Hi Philipp,

Glad to hear it!
Yes, we're currently (heh) working on signal level alignments.

Roger
