### ISSUE TITLE
Issues when running C3POa.py

### ISSUE THREAD

**Issue by kzeglinski** [rvolden/C3POa#11]
Hi, I've been trying to run C3POa.py but I'm running into some issues:
[c3poa_test.log](https://github.com/rvolden/C3POa/files/4572641/c3poa_test.log)

I thought that racon might be the problem, but when I look at the racon_messages there doesn't seem to be any errors:
[racon::Polisher::initialize] loaded target sequences 0.000064 s
[racon::Polisher::initialize] loaded sequences 0.000112 s
[racon::Polisher::initialize] loaded overlaps 0.000172 s
[racon::Polisher::initialize] aligned overlaps 0.000247 s
[racon::Polisher::initialize] transformed data into windows 0.000022 s
[racon::Polisher::polish] generated consensus 0.007131 s
[racon::Polisher::] total = 0.007923 s

So I'm not quite sure what's going wrong here. Any help would be greatly appreciated! Thanks :)

**Comment by rvolden** [comment]
Are you missing consensus sequences? The error you're getting is at the very end of the script where everything should be done. I probably just made a mistake with counting the sequences. You should check the number of sequences in the preprocessed fastq file as well as the consensus fasta output. I would expect that you'd retain about 85-99% of the sequences.

**Comment by kzeglinski** [comment]
Thanks for your reply! I just wanted to check that I'm counting things correctly as I'm getting a little confused with the output.
I counted the sequences in the R2C2_raw_reads.fastq using expr $(cat R2C2_raw_reads.fastq | wc -l) / 4 and got 3245.
I then counted the number of sequences in R2C2_Consensus.fasta using grep -c ">" R2C2_Consensus.fasta and got 4377. This seems a bit strange to me as the original input file only has 4000 sequences in it. Am I doing something wrong here?

**Comment by rvolden** [comment]
Hm that's weird. Can you post the commands/scripts that you ran for the preprocessing and consensus calling?

**Comment by kzeglinski** [comment]
Yep no worries. For preprocessing:
python3 ../../../C3POa/C3POa_preprocessing.py \
--input_fastq_file PAE72464_pass_9da53c78_222.fastq \
--splint_file ../../../C3POa/splint.fasta \
--output_path ./preprocessing2 \
--quality_cutoff 9 \
--read_length_cutoff 1300

Then for consensus:
python3 /home/u0001408/rca_test_analysis/C3POa/C3POa.py \
-m /home/u0001408/rca_test_analysis/C3POa/NUC.4.4.mat \
-l 1300 \
-d 1300 \
-r ./preprocessing/Splint1/R2C2_raw_reads.fastq \
-z \
-c ./config

**Comment by rvolden** [comment]
Not sure if this was a typo, but your input reads are coming from a different directory than your preprocessing output path

**Comment by kzeglinski** [comment]
Ah yes sorry, it's a typo! I thought maybe the preprocessing had gone wrong so I tried it again (with the same results). It should have been:

python3 ../../../C3POa/C3POa_preprocessing.py
--input_fastq_file PAE72464_pass_9da53c78_222.fastq
--splint_file ../../../C3POa/splint.fasta
--output_path ./preprocessing
--quality_cutoff 9
--read_length_cutoff 1300

Then for consensus:
python3 /home/u0001408/rca_test_analysis/C3POa/C3POa.py
-m /home/u0001408/rca_test_analysis/C3POa/NUC.4.4.mat
-l 1300
-d 1300
-r ./preprocessing/Splint1/R2C2_raw_reads.fastq
-z
-c ./config

**Comment by rvolden** [comment]
This isn't the most up-to-date version of C3POa, right? In any case, the consensus command is missing a path. Usually you would set the path to the preprocessing directory. At this point I'm still not sure why your output consensus fasta would be larger than your input

**Comment by kzeglinski** [comment]
I installed it about a fortnight ago, but just in case I re-downloaded C3POa and re-ran the preprocessing and consensus commands (this time with the missing path argument) as follows:

python3 /home/u0001408/rca_test_analysis/new_C3POa/C3POa/C3POa_preprocessing.py \
--input_fastq_file PAE72464_pass_9da53c78_222.fastq \
--splint_file /home/u0001408/rca_test_analysis/new_C3POa/C3POa/splint.fasta \
--output_path /home/u0001408/rca_test_analysis/test/results \
--quality_cutoff 9 \
--read_length_cutoff 1300

python3 /home/u0001408/rca_test_analysis/new_C3POa/C3POa/C3POa.py \
--matrix /home/u0001408/rca_test_analysis/new_C3POa/C3POa/NUC.4.4.mat \
--slencutoff 1300 \
--mdistcutoff 1300 \
--reads /home/u0001408/rca_test_analysis/test/results/Splint1/R2C2_raw_reads.fastq \
--zero \
--config config \
--path /home/u0001408/rca_test_analysis/test/results/

This seems to have solved the problem of the output consensus fasta being bigger than the input, now R2C2_Consensus.fasta contains 1459 reads. However, I'm still getting a similar error at the end:
/home/u0001408/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/u0001408/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/u0001408/rca_test_analysis/new_C3POa/C3POa/C3POa.py", line 708, in <module>
    main()
  File "/home/u0001408/rca_test_analysis/new_C3POa/C3POa/C3POa.py", line 703, in main
    sys.stderr.write("Consensus reads: {0}\t({1:.2f}%)\n".format(good[0], good[0]/total*100))
ZeroDivisionError: division by zero

**Comment by rvolden** [comment]
I took out the debug messages that were causing the error. You should maybe git pull and rerun just to be sure everything is in order.

**Comment by kzeglinski** [comment]
The errors are resolved now, thank you so much for all of your help!
