### ISSUE TITLE
Error in running C3POa.py

### ISSUE THREAD

**Issue by Joon-20** [rvolden/C3POa#2]
Hi, I am struggling with the C3POa.py script. 
I was able to run the preprocessing script without an issue and able to see the expected files.
But when I try to use these files for C3POa.py, I am getting this error : 

rm: cannot remove `/home/jlee20/dataset/ONT/PRJNA448331/consensus//tmp1': No such file or directory
/home/jlee20/dataset/ONT/PRJNA448331/raw_data/preprocessed/splint_reads/1/R2C2_raw_reads.fastq
Traceback (most recent call last):
  File "/camhpc/pkg/C3POa/1.0/centos6/C3POa.py", line 755, in <module>
    main()
  File "/camhpc/pkg/C3POa/1.0/centos6/C3POa.py", line 752, in main
    analyze_reads(read_list)
  File "/camhpc/pkg/C3POa/1.0/centos6/C3POa.py", line 713, in analyze_reads
    score_list_f = split_SW(name, forward, step=True)
  File "/camhpc/pkg/C3POa/1.0/centos6/C3POa.py", line 485, in split_SW
    run_water(step, seq1, seq2, totalLen, diag_dict, diag_set)
  File "/camhpc/pkg/C3POa/1.0/centos6/C3POa.py", line 459, in run_water
    diag_set, diag_dict)
  File "/camhpc/pkg/C3POa/1.0/centos6/C3POa.py", line 512, in parse_file
    for line in open(matrix_file):
FileNotFoundError: [Errno 2] No such file or directory: 'SW_PARSE.txt'

Can you let me know what is going wrong? My bash script is like this :

outpath=/home/jlee20/dataset/ONT/PRJNA448331/consensus/
path=/camhpc/pkg/C3POa/1.0/centos6/NUC.4.4.mat
path2=/camhpc/pkg/C3POa/1.0/centos6/config_file
path3=/home/jlee20/dataset/ONT/PRJNA448331/raw_data/preprocessed/splint_reads
fasta=consensus.fasta
output=$outpath$fasta
reads=/home/jlee20/dataset/ONT/PRJNA448331/raw_data/preprocessed/splint_reads/1/R2C2_raw_reads.fastq

python3 /camhpc/pkg/C3POa/1.0/centos6/C3POa.py --reads $reads --matrix $path --config $path2 --output $output -p $outpath

Thank you!
Joon

**Comment by rvolden** [comment]
Check on the water messages file to see what went wrong with the alignment. It looks like water didn't run

**Comment by Joon-20** [comment]
This was the message I found in the SW.txt file : 

Error: Argument 'yes' : Too many parameters 4/3
Thanks!

**Comment by rvolden** [comment]
Are you using our custom version of water or the normal EMBOSS version? This command should work with our version of water, but won't work the original.

**Comment by Joon-20** [comment]
Yes, we are using the 6.6.0 version of water.
Let me check with our IT people to see it is the custom version or not.
Thanks!

**Comment by Joon-20** [comment]
It worked perfectly well after using the correct custom version.
Thank you very much! -Joon
