### ISSUE TITLE
DNA splint sequence

### ISSUE THREAD

**Issue by callumparr** [rvolden/C3POa#3]
I wanted to try out this script using the SRA archived SIRV data but I cannot see a DNA splint sequence supplied. I think I worked out the sequence from find the fwd and rev primer sequences in a downloaded lambda DNA fasta file. But I am unsure whether this is the exact lambda DNA sequence you used or not

Sequence is included the: 

TGAGGCTGATGAGTTCCATATTTGAAAAGTTTTCATCACTACTTAGTTTTTTGATAGCTTCAAGCCAGAGTTGTCTTTTTCTATCTACTCTCATACAACCAATAAATGCTGAAATGAATTCTAAGCGGAGATCGCCTAGTGATTTTAAACTATTGCTGGCAGCATTCTTGAGTCCAATATAAAAGTATTGTGTACCTTTTGCTGGGTCAGGTTGTTCTTTAGGAGGAGTAAAAGGATCAAATGCACTAAACGAAACTGAAACAAGCGATCGAAAATATCCCTTT

**Comment by rvolden** [comment]
Yeah that looks fine to me
